# Generated by Django 6.0.1 on 2026-01-15 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=100)),
                ('dues', models.BigIntegerField()),
                ('dues_paid', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=256)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=256)),
                ('notes', models.TextField()),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.family')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shirt_size', models.CharField(max_length=10)),
                ('franchise_first', models.CharField(max_length=32)),
                ('franchise_second', models.CharField(max_length=32)),
                ('season', models.CharField(max_length=4)),
                ('returning', models.BooleanField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.person')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=4)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.person')),
            ],
        ),
    ]
